#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

groestlcoin_mp - Plugin to monitor groestlcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/groestlcoin.
Edit the GROESTLCOIN_DATADIR setting to specify the location of your groestlcoin data directory.
Edit the GROESTLCOIN_CLI setting to specify the location of groestlcoin-cli.

=head1 NOTES

Uses env.GROESTLCOIN_CLI and env.GROESTLCOIN_DATADIR in /etc/munin/plugin-conf.d/groestlcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title groestlcoind memory pool'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel value'
	echo 'graph_category groestlcoind'
	echo 'size.label size'
	echo 'size.type GAUGE'
	echo 'size.max 1000000'
	exit 0
fi

# ${GROESTLCOIN_CLI} getmempoolinfo
#{
#  "size": 11853,
#  "bytes": 45560692,
#  "usage": 89999136,
#  "maxmempool": 300000000,
#  "mempoolminfee": 0.00000000
#}

TFILE=/tmp/munin-groestlcoin-mp-$$
${GROESTLCOIN_CLI} -datadir=$GROESTLCOIN_DATADIR getmempoolinfo > $TFILE

echo "size.value `grep size $TFILE | grep -o '[0-9]*'`"

rm $TFILE
