#!/bin/sh
# -*- sh -*-

: << =cut

=head1 NAME

groestlcoin_vm - Plugin to monitor groestlcoin daemon.

=head1 CONFIGURATION

Settings are stored in /etc/munin/plugin-conf.d/groestlcoin.
Edit the GROESTLCOIN_DATADIR setting to specify the location of your groestlcoin data directory.
Edit the GROESTLCOIN_CLI setting to specify the location of groestlcoin-cli.

=head1 NOTES

Uses env.GROESTLCOIN_CLI and env.GROESTLCOIN_DATADIR in /etc/munin/plugin-conf.d/groestlcoin

=head1 AUTHOR

shsmith

=head1 LICENSE

GPLv2

=head1 MAGIC MARKERS

 #%# family=auto
 #%# capabilities=autoconf

=cut

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title groestlcoind process memory'
	echo 'graph_args --base 1024 -l 0'
	echo 'graph_vlabel bytes'
	echo 'graph_category groestlcoind'
	echo 'vmsize.label VmSize'
	echo 'vmsize.type GAUGE'
	echo 'vmsize.cdef vmsize,1024,*'
	echo 'vmrss.label VmRss'
	echo 'vmrss.type GAUGE'
	echo 'vmrss.cdef vmrss,1024,*'
	echo 'vmswap.label VmSwap'
	echo 'vmswap.type GAUGE'
	echo 'vmswap.cdef vmswap,1024,*'
	exit 0
fi

pid=`pidof groestlcoind`
if [ "$pid" = "" ]; then
	exit 0
fi
echo "vmsize.value `grep VmSize /proc/$pid/status | grep -o '[0-9]*'`"
echo "vmrss.value `grep VmRSS /proc/$pid/status | grep -o '[0-9]*'`"
echo "vmswap.value `grep VmSwap /proc/$pid/status | grep -o '[0-9]*'`"

exit 0

